config/routes.rb
Rails.application.routes.draw do



  devise_for :users



  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index]

  get 'home/about', to: 'homes#about', as: 'about'

  root to: 'homes#top'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy



  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user! # ログインユーザーのみアクセス可能とする

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.new(book_comment_params)
    @comment.user = current_user
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = 'Comment created successfully.'
    else
      flash[:error] = 'Error creating comment.'
    end

    redirect_back(fallback_location: root_path) # 元の画面に遷移する
  end

  def destroy
    @comment = BookComment.find(params[:id])


    if @comment.user == current_user
      @comment.destroy
      flash[:success] = 'Comment deleted successfully.'
    else
      flash[:error] = 'You are not authorized to delete this comment.'
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy], except: [:index, :show]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(books_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    @book_comment = BookComment.new
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = current_user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(books_params)
      flash[:success] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      flash[:error] = 'Error updating user profile.'
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  # 投稿データのストロングパラメータ
  private

  def books_params
    params.require(:book).permit(:title, :body)
  end

  private

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!  # ログインしているユーザーのみアクセス許可

  def create
  @book = Book.find(params[:book_id])
  @favorite = current_user.favorites.new(book: @book)
  @favorite.save
  redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book: @book)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]



  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
    @books = current_user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:success] = "Profile successfully updated."
     redirect_to user_path(@user.id)
     else
      flash.now[:error] = 'Error updating user profile.' # エラーメッセージの設定
      render :edit
     end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_with model:book,local:true do |f| %>
  <h2 class="mt-3">New book</h2>
  <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>
  <div class="form-group">
  <%= f.label :opinion %>
  <%= f.text_area :body %>
  </div>

  <div class="form-group">
  <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<p id="notice"><%= flash[:success] %></p>
<% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <%= form_with(model: @book, url: book_path(@book), method: :patch) do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>

    <%= link_to 'Show', book_path(@book) %> | <%= link_to 'Back', books_path %>


    </div>

  </div>
</div>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<p id="notice"><%= flash[:success] %></p>

  <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: current_user %>
      <%= render 'books/book', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(100, 100) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fa-solid fa-heart"></i>
                  <% end %>
                  <%= book.favorites.count %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                  <%= book.favorites.count %>
                <% end %>
                </td>
                <td>
                  <p>コメント数：<%= @book.book_comments.count %></p>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= flash[:success] %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
    <%= render 'users/userinfo', user: @book.user %>

    <%= render 'books/book', book: @books %>
   </div>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>

  <table class="table">
  		  <tbody>
  		    <tr>
  		      <td>
  		         <%= image_tag @book.user.get_profile_image(100, 100) %>
  		         <br>
               <%= link_to @book.user.name, user_path(@book.user) %>
  		       </td>
  		       <td>
              <%= link_to @book.title, book_path(@book) %>
             </td>
  		        <td>
              <%= @book.body %>
              </td>
              <td>

                  <div class="favorite-button">
                  <% if @book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <i class="fas fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <i class="far fa-heart"></i>
                    <% end %>
                  <% end %>

                  <%= @book.favorites.count %>
                </div>

                </td>
              <td>
                 <p>コメント数：<%= @book.book_comments.count %></p>
              </td>
            <td>
              <% if @book.user == current_user %>
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
               <%= link_to 'Destroy', book_path(@book), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
        </tr>
      </tbody>
</table>


  <div>
    <tbody>

    <tr>

  <% @book.book_comments.each do |book_comment| %>
    <td>
    <%= image_tag book_comment.user.get_profile_image(100, 100) %>
    <%= link_to book_comment.user.name, user_path(book_comment.user) %>
    </td>

    <td>
    <%= book_comment.comment %>
    </td>
    <td>
    <% if book_comment.user == current_user %>
      <%= link_to 'Destroy', book_book_comment_path(@book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
    <% end %>
    </td>
  <% end %>
  </tr>
  </tbody>
</div>
<div>
  <%= form_with model: [@book, @book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>
</div>

app/views/homes/about.html.erb
<script src="https://kit.fontawesome.com/6ed17a6157.js" crossorigin="anonymous"></script>

<h1>Welcome to<i class="fas fa-book"></i><strong>Bookers!</strong></h1>

<p>CopyRight Infratop.inc</p>

app/views/homes/top.html.erb
<script src="https://kit.fontawesome.com/6ed17a6157.js" crossorigin="anonymous"></script>


<p id="notice"><%= flash[:notice] %></p>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>

<p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

<p>you can share and exchange  your opinions , inpressions , and emotions</p>

<p> about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
  <div class="row">
       <%= link_to 'Log in', new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
  </div>
  <div class="row">
    <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
  </div>
</div>

<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6ed17a6157.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <header>
    <nav class=" navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand " href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">



       <% if user_signed_in? %>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
    <%= link_to user_path(current_user), class: "nav-link text-light" do %>
      <i class="fas fa-home"></i> Home
    <% end %>
  </li>
    <li class="nav-item">
      <%= link_to users_path, class: "nav-link text-light" do %>
        <i class="fas fa-users"></i> Users
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to books_path, class: "nav-link text-light" do %>
        <i class="fas fa-book-open"></i> Books
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
        <i class="fas fa-sign-out-alt"></i> Log out
      <% end %>
    </li>
  </ul>


<% else %>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to root_path, class: "nav-link text-light" do %>
        <i class="fas fa-home"></i> Home
      <% end %>
    </li>
    <li class="nav-item">
  <%= link_to about_path, class: "nav-link text-light" do %>
    <i class="fas fa-link"></i> About
  <% end %>
</li>
    <li class="nav-item">
      <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
        <i class="fas fa-user-plus"></i> Sign up
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_user_session_path, class: "nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i> Log in
      <% end %>
    </li>
  </ul>
<% end %>
        </div>
      </div>
    </nav>
  </header>
  <%= yield %>
</body>
</html>

app/views/users/_userinfo.html.erb
<script src="https://kit.fontawesome.com/6ed17a6157.js" crossorigin="anonymous"></script>

<h2>User info</h2>

<%= image_tag user.get_profile_image(100, 100) %>

<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">


  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>

</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <%= @user.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<main>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
  <%= form_with model: @user do |f| %>
  <div class="form-group">
  <label for="inputName">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class:"form-control name"%>
  </div>

  <div class="form-group">
  <label for="inputImage">Image</label><br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  </div>

  <div class="form-group">
  <label for="inputIntroduction">Introduction</label><br>
  <%= f.text_area :introduction, id: "inputIntroduction", class: "form-control introduction" %>
   </div>

  <div class="form-group">
  <%= f.submit "Update User", class: "btn btn-secondary" %>
   </div>
  <% end %>
   </div>
  </div>
</div>
</main>



<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<p id="notice"><%= flash[:success] %></p>
<p id="error"><%= flash.now[:error] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: current_user %>
      <%= render 'books/book', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(100, 100) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to 'Show', user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= flash[:success] %></p>
<p id="notice"><%= flash[:notice] %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
    <%= render 'users/userinfo', user: @user %>

    <%= render 'books/book', book: @book %>
   </div>

<div class="col-md-8 offset-md-1">
   <h2>Books</h2>
      <table class="table table-hover table-inverse">
   <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
  <tr>
    <td>
      <%= link_to image_tag(book.user.get_profile_image(100, 100)), user_path(book.user)%>
    </td>
    <td>
        <%= link_to book.title,book_path(book.id) %>
    </td>
    <td>
      <%= book.body %>
    </td>
    <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fa-solid fa-heart"></i>
                  <% end %>
                  <%= book.favorites.count %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="far fa-heart"></i>
                  <% end %>
                  <%= book.favorites.count %>
                <% end %>
                </td>
    <td>
       <p>コメント数：<%= book.book_comments.count %></p>
    </td>
  </tr>
<% end %>
</tbody>
      </table>
    </div>
  </div>
</div>